### ISSUE TITLE
Practice: Build Superheroes app:  Android Basics in Compose  

### ISSUE THREAD

**Issue by sanskar10100** [google-developer-training/basic-android-kotlin-compose-training-superheroes#2]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-superheroes

**In which task and step of the codelab can this issue be found?**
Task 4: Display List

**Describe the problem**
The design spec provided in the codelab is incorrect for replicating the list item screenshot. Specifically, setting the list item size to `74.dp` results in the text being cut off. The solution code uses `72.dp` size for the image alone, which is what should've been specified in the spec.

**Steps to reproduce?**
1. Open the task in the codelab
2. Reproduce the design using the font resources specified earlier
3. Set the height of the card to 74 dp
4. Text/Image is/are cut off, and the image is improperly positioned.

**Versions**
_Android Studio Chimunk | 2021.2.1 Patch 1_
_API version of the emulator: 30_
_Compose Version: 1.1.0-beta01_

**Additional information**
![image](https://user-images.githubusercontent.com/22092047/182357259-43476cd5-fcd3-4acb-b115-7c22640da4a5.png)

On setting no height on the card and specifying a size of `72.dp` for the image:
![image](https://user-images.githubusercontent.com/22092047/182357711-9730208e-b7b4-41de-8576-a1c35d810f0c.png)

**Comment by osuleymanova** [comment]
@sanskar10100 
Tanks for reaching out to us and reporting this issue. It is fixed:
![Uploading Screen Shot 2022-11-09 at 5.13.47 PM.png…]()
