### ISSUE TITLE
Practice: Build Superheroes app:  Android Basics in Compose  

### ISSUE THREAD

**Issue by casanovaP** [google-developer-training/basic-android-kotlin-compose-training-superheroes#3]
hi guys,

the Strings content for Strings xml are missing... not to be found on step 2. Get started, nor 3
i will just create some strings myself, but just FYI, they are missing
thanks for all the lessons and knowledge!! its good stuff ;)
you guys rock

**Comment by android-dev-lxl** [comment]
@TenHorizons 
@casanovaP 
Thank you for reaching out to us, glad the the course was helpful.
We expect students to come up with their own content and design since this is a practice set rather than a codelab.
