### ISSUE TITLE
Practice: Build Superheroes app:  Android Basics in Compose  

### ISSUE THREAD

**Issue by sandstroms** [google-developer-training/basic-android-kotlin-compose-training-superheroes#4]
In task 6, the given git command to clone the repository references an invalid Git repository. It should be `$ git clone https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes.git` instead of `$ git clone https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes-app.git` (note the first clone command references the correct Git repository which does not have the "app" suffix).

**Comment by osuleymanova** [comment]
@sandstroms 
Thanks for reaching out to us and reporting this typo. It is fixed.
