### ISSUE TITLE
Practice: Build Superheroes app:  Android Basics with Compose  

### ISSUE THREAD

**Issue by ppjanka** [google-developer-training/basic-android-kotlin-compose-training-superheroes#5]
The list item height specification of 72.dp should apply to the Row content height (excluding padding), i.e., as marked (with padding) it should be 72 + 2*16 = 104.dp.

**Comment by jayeshmann** [comment]
Correct! I support this change.

**Comment by android-dev-lxl** [comment]
@ppjanka @jayeshmann 
We are setting minHeight to 72dp. 
Look into the documentation for further information: https://developer.android.com/reference/kotlin/androidx/compose/ui/unit/Constraints#minHeight()

https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/blob/64cb06ff8e04568f012602b9f07fa7a644bdcb96/app/src/main/java/com/example/superheroes/HeroesScreen.kt#LL118C25-L118C34
