### ISSUE TITLE
Practice: Build Superheroes app:  Android Basics with Compose  

### ISSUE THREAD

**Issue by JohnnyJagatpal** [google-developer-training/basic-android-kotlin-compose-training-superheroes#7]
The image  of the list item shows a card with a height of 72 dp. According to the solution the row height inside the card should be 72 dp. Therefore the card size should be 72 dp + 2 * 16 dp = 104  dp. Also that the List height should be flexible should be mentioned.

**Comment by osuleymanova** [comment]
Duplicate of #5
